In [ ]:
import tensorflow as tf
import numpy as np

#Introduction to tensors

In [ ]:
rank_zero_tensor = tf.constant(10)
print(rank_zero_tensor)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
rank_one_tensor = tf.constant([1.0,2.0,3.0])
print(rank_one_tensor)
rank_one_tensor_new = tf.constant([1,2,3])
print(rank_one_tensor_new)


tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
rank_two_tensor = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
print(rank_two_tensor)
rank_two_tensor_up = tf.constant([[1,2,3], [4,5,6], [7,8,9]], dtype=tf.float16) #we can setup data type by ourselve
print(rank_two_tensor_up)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float16)


In [ ]:
rank_three_tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(rank_three_tensor)


tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


### Tensor to numpy

In [ ]:
rank_two_tensor.numpy() #tensor to numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [ ]:
rank_three_tensor.numpy()

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [ ]:
a = tf.constant([[2,3], [8,9]])
b = tf.constant([[6,7], [11,12]])
print(tf.add(a,b))
print(tf.multiply(a,b))
print(tf.matmul(a,b))


tf.Tensor(
[[ 8 10]
 [19 21]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 12  21]
 [ 88 108]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 45  50]
 [147 164]], shape=(2, 2), dtype=int32)


In [ ]:
print(a+b) #element-wise addition
print(a*b) #element-wise multiplication
print(a@b) #matrix multiplication


tf.Tensor(
[[ 8 10]
 [19 21]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 12  21]
 [ 88 108]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 45  50]
 [147 164]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.zeros([2,3,4,5])

In [ ]:
print("type of every element", d.dtype)
print("number of dimension", d.ndim)
print("shape", d.shape)
print("total number of elemets", tf.size(d))
print("elements of axis zero", d.shape[0])
print("elements of axis one", d.shape[1])
print("elements of axis two", d.shape[2])
print("elements of axis three", d.shape[3])

type of every element <dtype: 'float32'>
number of dimension 4
shape (2, 3, 4, 5)
total number of elemets tf.Tensor(120, shape=(), dtype=int32)
elements of axis zero 2
elements of axis one 3
elements of axis two 4
elements of axis three 5


In [ ]:
rank1_tensor = tf.constant([1,2,3,4,5,6,7,8])
print("oth element", rank1_tensor[0])
print("first element", rank1_tensor[1])
print("before 4", rank1_tensor[:3])

oth element tf.Tensor(1, shape=(), dtype=int32)
first element tf.Tensor(2, shape=(), dtype=int32)
before 4 tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
rank2_tensor = tf.constant([[1,2], [5,6]])
print("two will be then" , rank2_tensor[0,1])
print("6 will be then", rank2_tensor[1,1])


two will be then tf.Tensor(2, shape=(), dtype=int32)
6 will be then tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
rank_three_tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(rank_three_tensor)
print(rank_three_tensor[1,1,2])

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


#Reshaping

In [ ]:
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
print(var_x)
print(var_x.shape)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>
(3, 1)


In [ ]:
reshaped = tf.reshape(var_x, [1,3])

In [ ]:
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [ ]:
print(rank_three_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
tf.reshape(rank_three_tensor, [-1]) #Whatever fits

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)>

In [ ]:
print(rank_three_tensor.shape)
reshape_three = tf.reshape(rank_three_tensor, [3,2,2]) 
print(reshape_three)

(2, 2, 3)
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)


#Data type

In [ ]:
tensor_16 = tf.constant([2.2,3.5,8.6])
print(tensor_16)

tf.Tensor([2.2 3.5 8.6], shape=(3,), dtype=float32)


In [ ]:
tf_u8 = tf.cast (tensor_16,dtype=tf.uint8) #lost decimal part
print(tf_u8 )

tf.Tensor([2 3 8], shape=(3,), dtype=uint8)


tf.convert_to_tensor
Most object classes like NumPy's ndarray, TensorShape, Python lists, and tf.Variable will all get converted to Tensor automatically.

In [ ]:
rank_three_tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(rank_three_tensor)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
print(tf.squeeze(rank_three_tensor))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
import torch

In [ ]:
tensor = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
tensor.shape

torch.Size([3, 4])

In [ ]:
print(tensor.size())

torch.Size([3, 4])


In [ ]:
len(tensor.shape) #this is the rank

2

In [ ]:
torch.tensor(tensor.shape).prod() #total number of element

tensor(12)

In [ ]:
tensor.numel() #number of elements

12

In [ ]:
tensor.reshape(1,12)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
tensor.reshape(6,2) #The prod same 12


tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
print(tensor.reshape(1,12).squeeze())
print(tensor.reshape(1,12).squeeze().shape) #removed all axis with dimension 1


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
torch.Size([12])


In [ ]:
print(tensor.reshape(1,12).squeeze().unsqueeze(dim=0))
print(tensor.reshape(1,12).squeeze().unsqueeze(dim=0).shape) #getting 1 back

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])


flatten converts 2d to 1d array

In [ ]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [ ]:
t= torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(tensor.shape)

torch.Size([3, 4])


In [ ]:
flated = flatten(t)
print(flated.shape) #2d to 1d and squeezed that is what flatten does


torch.Size([12])


In [ ]:
tensor= torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
tensor.reshape(12)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
t1 = torch.tensor([[1,2], [3,4]])
t2 = torch.tensor([[8,9], [10,11]])

In [ ]:
new = torch.cat([t1,t2], dim=0)

In [ ]:
print(new.shape)

torch.Size([4, 2])


In [ ]:
a = tf.constant([ [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]],])
print(a.shape)

(3, 2, 5)


In [ ]:
b = tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])
print(len(b.shape))

3


In [ ]:
tensor = tf.constant([2, 14, 10, 12, 15, 3, 2, 5, 15, 78])
print(tensor[:5])

tf.Tensor([ 2 14 10 12 15], shape=(5,), dtype=int32)


In [ ]:
tensor[0::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2, 10, 15,  2, 15], dtype=int32)>

In [ ]:
t = [

[3, 2, 1],

[6, 5, 4],

[9, 8, 7]

]

print(t[1][0])

6
